//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLAzureMW.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLAzureMW.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLAzureMW has finished analysis.  Any issues discovered will be reported above..
        /// </summary>
        internal static string AnalysisComplete {
            get {
                return ResourceManager.GetString("AnalysisComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure requires {0} extension on your user name.  Do you want me to add it for you?.
        /// </summary>
        internal static string AzureUserName {
            get {
                return ResourceManager.GetString("AzureUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure User Name Requirements.
        /// </summary>
        internal static string AzureUserNameWarning {
            get {
                return ResourceManager.GetString("AzureUserNameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular table dependencies have been found on the following tables:.
        /// </summary>
        internal static string CircularDependencies {
            get {
                return ResourceManager.GetString("CircularDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility Checks -- {0}.
        /// </summary>
        internal static string CompatibilityChecks {
            get {
                return ResourceManager.GetString("CompatibilityChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory Stored Procedures -- {0}.
        /// </summary>
        internal static string CompatibilityChecksActiveDirectory {
            get {
                return ResourceManager.GetString("CompatibilityChecksActiveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup and Restore Tables -- {0}.
        /// </summary>
        internal static string CompatibilityChecksBackupRestore {
            get {
                return ResourceManager.GetString("CompatibilityChecksBackupRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Data Capture -- {0}.
        /// </summary>
        internal static string CompatibilityChecksCDC {
            get {
                return ResourceManager.GetString("CompatibilityChecksCDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Data Capture Tables -- {0}.
        /// </summary>
        internal static string CompatibilityChecksCDCT {
            get {
                return ResourceManager.GetString("CompatibilityChecksCDCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Controls -- {0}.
        /// </summary>
        internal static string CompatibilityChecksDataControls {
            get {
                return ResourceManager.GetString("CompatibilityChecksDataControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributed Queries Stored Procedures -- {0}.
        /// </summary>
        internal static string CompatibilityChecksDistributedQueries {
            get {
                return ResourceManager.GetString("CompatibilityChecksDistributedQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Engine Stored Procedures -- {0}.
        /// </summary>
        internal static string CompatibilityChecksEngineSP {
            get {
                return ResourceManager.GetString("CompatibilityChecksEngineSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Text Search Stored Procedures -- {0}.
        /// </summary>
        internal static string CompatibilityChecksFullTextSearch {
            get {
                return ResourceManager.GetString("CompatibilityChecksFullTextSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Extended Stored Procedures -- {0}.
        /// </summary>
        internal static string CompatibilityChecksGeneralExtended {
            get {
                return ResourceManager.GetString("CompatibilityChecksGeneralExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General T-SQL -- {0}.
        /// </summary>
        internal static string CompatibilityChecksGeneralTSQL {
            get {
                return ResourceManager.GetString("CompatibilityChecksGeneralTSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration Services Tables -- {0}.
        /// </summary>
        internal static string CompatibilityChecksIntegrationServicesTable {
            get {
                return ResourceManager.GetString("CompatibilityChecksIntegrationServicesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Shipping -- {0}.
        /// </summary>
        internal static string CompatibilityChecksLogShipping {
            get {
                return ResourceManager.GetString("CompatibilityChecksLogShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Mail Stored Procedures -- {0}.
        /// </summary>
        internal static string CompatibilityChecksMail {
            get {
                return ResourceManager.GetString("CompatibilityChecksMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Maintenance Plans -- {0}.
        /// </summary>
        internal static string CompatibilityChecksMaintenance {
            get {
                return ResourceManager.GetString("CompatibilityChecksMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata Functions -- {0}.
        /// </summary>
        internal static string CompatibilityChecksMetadataFunction {
            get {
                return ResourceManager.GetString("CompatibilityChecksMetadataFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OLE Automation Stored Procedures -- {0}.
        /// </summary>
        internal static string CompatibilityChecksOLEAutomationSP {
            get {
                return ResourceManager.GetString("CompatibilityChecksOLEAutomationSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OLEDB Tables -- {0}.
        /// </summary>
        internal static string CompatibilityChecksOLEDBTable {
            get {
                return ResourceManager.GetString("CompatibilityChecksOLEDBTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiler Stored Procedures -- {0}.
        /// </summary>
        internal static string CompatibilityChecksProfilerSP {
            get {
                return ResourceManager.GetString("CompatibilityChecksProfilerSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replication Stored Procedures -- {0}.
        /// </summary>
        internal static string CompatibilityChecksReplicationSP {
            get {
                return ResourceManager.GetString("CompatibilityChecksReplicationSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replication Tables -- {0}.
        /// </summary>
        internal static string CompatibilityChecksReplicationTable {
            get {
                return ResourceManager.GetString("CompatibilityChecksReplicationTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rowset Functions -- {0}.
        /// </summary>
        internal static string CompatibilityChecksRowsetFunction {
            get {
                return ResourceManager.GetString("CompatibilityChecksRowsetFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Functions -- {0}.
        /// </summary>
        internal static string CompatibilityChecksSecurityFunction {
            get {
                return ResourceManager.GetString("CompatibilityChecksSecurityFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Stored Procedures -- {0}.
        /// </summary>
        internal static string CompatibilityChecksSecuritySP {
            get {
                return ResourceManager.GetString("CompatibilityChecksSecuritySP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Mail Stored Procedures -- {0}.
        /// </summary>
        internal static string CompatibilityChecksSQLMailSP {
            get {
                return ResourceManager.GetString("CompatibilityChecksSQLMailSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server Agent Stored Procedures -- {0}.
        /// </summary>
        internal static string CompatibilityChecksSQLServerAgentSP {
            get {
                return ResourceManager.GetString("CompatibilityChecksSQLServerAgentSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server Agent Tables -- {0}.
        /// </summary>
        internal static string CompatibilityChecksSQLServerAgentTable {
            get {
                return ResourceManager.GetString("CompatibilityChecksSQLServerAgentTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Catalog Views -- {0}.
        /// </summary>
        internal static string CompatibilityChecksSystemCatalogView {
            get {
                return ResourceManager.GetString("CompatibilityChecksSystemCatalogView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Functions -- {0}.
        /// </summary>
        internal static string CompatibilityChecksSystemFunction {
            get {
                return ResourceManager.GetString("CompatibilityChecksSystemFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Statistical Functions -- {0}.
        /// </summary>
        internal static string CompatibilityChecksSystemStatisticalFunction {
            get {
                return ResourceManager.GetString("CompatibilityChecksSystemStatisticalFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unclassified -- {0}.
        /// </summary>
        internal static string CompatibilityChecksUnclassified {
            get {
                return ResourceManager.GetString("CompatibilityChecksUnclassified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Database.
        /// </summary>
        internal static string CreateDatabase {
            get {
                return ResourceManager.GetString("CreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string CreateDatabaseBasicEdition {
            get {
                return ResourceManager.GetString("CreateDatabaseBasicEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        internal static string CreateDatabaseBusinessEdition {
            get {
                return ResourceManager.GetString("CreateDatabaseBusinessEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium.
        /// </summary>
        internal static string CreateDatabasePremiumEdition {
            get {
                return ResourceManager.GetString("CreateDatabasePremiumEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50 GB.
        /// </summary>
        internal static string CreateDatabaseSizeFiftyGB {
            get {
                return ResourceManager.GetString("CreateDatabaseSizeFiftyGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 GB.
        /// </summary>
        internal static string CreateDatabaseSizeFiveGB {
            get {
                return ResourceManager.GetString("CreateDatabaseSizeFiveGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 GB.
        /// </summary>
        internal static string CreateDatabaseSizeFiveHundredGB {
            get {
                return ResourceManager.GetString("CreateDatabaseSizeFiveHundredGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 MB.
        /// </summary>
        internal static string CreateDatabaseSizeFiveHundredMB {
            get {
                return ResourceManager.GetString("CreateDatabaseSizeFiveHundredMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400 GB.
        /// </summary>
        internal static string CreateDatabaseSizeFourHundredGB {
            get {
                return ResourceManager.GetString("CreateDatabaseSizeFourHundredGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 GB.
        /// </summary>
        internal static string CreateDatabaseSizeFourtyGB {
            get {
                return ResourceManager.GetString("CreateDatabaseSizeFourtyGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 GB.
        /// </summary>
        internal static string CreateDatabaseSizeOneGB {
            get {
                return ResourceManager.GetString("CreateDatabaseSizeOneGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150 GB.
        /// </summary>
        internal static string CreateDatabaseSizeOneHundredFiftyGB {
            get {
                return ResourceManager.GetString("CreateDatabaseSizeOneHundredFiftyGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100 GB.
        /// </summary>
        internal static string CreateDatabaseSizeOneHundredGB {
            get {
                return ResourceManager.GetString("CreateDatabaseSizeOneHundredGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100 MB.
        /// </summary>
        internal static string CreateDatabaseSizeOneHundredMB {
            get {
                return ResourceManager.GetString("CreateDatabaseSizeOneHundredMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 GB.
        /// </summary>
        internal static string CreateDatabaseSizeTenGB {
            get {
                return ResourceManager.GetString("CreateDatabaseSizeTenGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 GB.
        /// </summary>
        internal static string CreateDatabaseSizeThirtyGB {
            get {
                return ResourceManager.GetString("CreateDatabaseSizeThirtyGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300 GB.
        /// </summary>
        internal static string CreateDatabaseSizeThreeHundredGB {
            get {
                return ResourceManager.GetString("CreateDatabaseSizeThreeHundredGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 GB.
        /// </summary>
        internal static string CreateDatabaseSizeTwentyGB {
            get {
                return ResourceManager.GetString("CreateDatabaseSizeTwentyGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 GB.
        /// </summary>
        internal static string CreateDatabaseSizeTwoGB {
            get {
                return ResourceManager.GetString("CreateDatabaseSizeTwoGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 250 GB.
        /// </summary>
        internal static string CreateDatabaseSizeTwoHundredFiftyGB {
            get {
                return ResourceManager.GetString("CreateDatabaseSizeTwoHundredFiftyGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200 GB.
        /// </summary>
        internal static string CreateDatabaseSizeTwoHundredGB {
            get {
                return ResourceManager.GetString("CreateDatabaseSizeTwoHundredGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string CreateDatabaseStandardEdition {
            get {
                return ResourceManager.GetString("CreateDatabaseStandardEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        internal static string CreateDatabaseWebEdition {
            get {
                return ResourceManager.GetString("CreateDatabaseWebEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure SQL DB is in the process of creating your database.  Please wait ....
        /// </summary>
        internal static string CreateDBInProcess {
            get {
                return ResourceManager.GetString("CreateDBInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collation {0}.
        /// </summary>
        internal static string DatabaseCollation {
            get {
                return ResourceManager.GetString("DatabaseCollation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database {0} created!.
        /// </summary>
        internal static string DatabaseCreated {
            get {
                return ResourceManager.GetString("DatabaseCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Exists.
        /// </summary>
        internal static string DatabaseExists {
            get {
                return ResourceManager.GetString("DatabaseExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data will be uploaded before foreign keys are added..
        /// </summary>
        internal static string DataUploadBeforeForeignKeys {
            get {
                return ResourceManager.GetString("DataUploadBeforeForeignKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Database.
        /// </summary>
        internal static string DeleteDatabase {
            get {
                return ResourceManager.GetString("DeleteDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Azure SQL DB is in the process of being deleted..
        /// </summary>
        internal static string DeleteDBinProcess {
            get {
                return ResourceManager.GetString("DeleteDBinProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich Text Format files (*.rtf)|*.rtf|TSQL File (*.sql)|*.sql|All files (*.*)|*.*.
        /// </summary>
        internal static string DialogFilterRTF {
            get {
                return ResourceManager.GetString("DialogFilterRTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSQL File (*.sql)|*.sql|Rich Text Format files (*.rtf)|*.rtf|All files (*.*)|*.*.
        /// </summary>
        internal static string DialogFilterSQLRTF {
            get {
                return ResourceManager.GetString("DialogFilterSQLRTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Profiler trace files (*.trc)|*.trc|All files (*.*)|*.*.
        /// </summary>
        internal static string DialogFilterTrace {
            get {
                return ResourceManager.GetString("DialogFilterTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSQL files (*.sql)|*.sql|All files (*.*)|*.*.
        /// </summary>
        internal static string DialogFilterTSQL {
            get {
                return ResourceManager.GetString("DialogFilterTSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select SQL Profiler trace file to analyze.
        /// </summary>
        internal static string DialogTitleTrace {
            get {
                return ResourceManager.GetString("DialogTitleTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select TSQL file.
        /// </summary>
        internal static string DialogTitleTSQL {
            get {
                return ResourceManager.GetString("DialogTitleTSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovering: {0} of {1}.
        /// </summary>
        internal static string Discovering {
            get {
                return ResourceManager.GetString("Discovering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is Encrypted.
        /// </summary>
        internal static string Encrypted {
            get {
                return ResourceManager.GetString("Encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Creating Database.
        /// </summary>
        internal static string ErrorCreatingDB {
            get {
                return ResourceManager.GetString("ErrorCreatingDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis failed: {0}.
        /// </summary>
        internal static string MessageAnalysisFailed {
            get {
                return ResourceManager.GetString("MessageAnalysisFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis failed at {0}.
        /// </summary>
        internal static string MessageAnalysisFailedAt {
            get {
                return ResourceManager.GetString("MessageAnalysisFailedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete database {0}?.
        /// </summary>
        internal static string MessageAreYouSure {
            get {
                return ResourceManager.GetString("MessageAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating number of records to process.
        /// </summary>
        internal static string MessageCalculatingNumberOrRecs {
            get {
                return ResourceManager.GetString("MessageCalculatingNumberOrRecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating size ....
        /// </summary>
        internal static string MessageCalculatingSize {
            get {
                return ResourceManager.GetString("MessageCalculatingSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled!.
        /// </summary>
        internal static string MessageCanceled {
            get {
                return ResourceManager.GetString("MessageCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled processing at {0} ....
        /// </summary>
        internal static string MessageCanceledProcessing {
            get {
                return ResourceManager.GetString("MessageCanceledProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating DROP scripts ....
        /// </summary>
        internal static string MessageCreatingDropScripts {
            get {
                return ResourceManager.GetString("MessageCreatingDropScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, database already exists.  Please choose another name..
        /// </summary>
        internal static string MessageDatabaseExists {
            get {
                return ResourceManager.GetString("MessageDatabaseExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder to process (includes all sub folders).
        /// </summary>
        internal static string MessageDirectoryToProcess {
            get {
                return ResourceManager.GetString("MessageDirectoryToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute script against destination server?.
        /// </summary>
        internal static string MessageExecuteScript {
            get {
                return ResourceManager.GetString("MessageExecuteScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but the file you entered does not exist.
        /// </summary>
        internal static string MessageFileDoesNotExists {
            get {
                return ResourceManager.GetString("MessageFileDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update file {0} .
        /// </summary>
        internal static string MessageFileoverwriteFailure {
            get {
                return ResourceManager.GetString("MessageFileoverwriteFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated file {0} .
        /// </summary>
        internal static string MessageFileoverwriteSuccess {
            get {
                return ResourceManager.GetString("MessageFileoverwriteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File to process.
        /// </summary>
        internal static string MessageFileToProcess {
            get {
                return ResourceManager.GetString("MessageFileToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No analysis done on script.
        ///Processing finished at {0} -- UTC -&gt; {1}
        ///Total processing time: {2}.
        /// </summary>
        internal static string MessageFinishedNoAnalysis {
            get {
                return ResourceManager.GetString("MessageFinishedNoAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis completed at {0} -- UTC -&gt; {1}
        ///Any issues discovered will be reported above.
        ///Total processing time: {2}.
        /// </summary>
        internal static string MessageFinishedWithAnalysis {
            get {
                return ResourceManager.GetString("MessageFinishedWithAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but the folder path that you entered does not exist.
        /// </summary>
        internal static string MessageFolderDoesNotExists {
            get {
                return ResourceManager.GetString("MessageFolderDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select TSQL root folder for processing.
        /// </summary>
        internal static string MessageFolderToProcess {
            get {
                return ResourceManager.GetString("MessageFolderToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  hour, .
        /// </summary>
        internal static string MessageHour {
            get {
                return ResourceManager.GetString("MessageHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  hours, .
        /// </summary>
        internal static string MessageHours {
            get {
                return ResourceManager.GetString("MessageHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  minute and .
        /// </summary>
        internal static string MessageMinute {
            get {
                return ResourceManager.GetString("MessageMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  minutes and .
        /// </summary>
        internal static string MessageMinutes {
            get {
                return ResourceManager.GetString("MessageMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The files below contain modified T-SQL statements and are available in : {0}. Do you want to overwrite the original files in {1} with these changes? A copy of the original files are available here :{2}.
        /// </summary>
        internal static string MessageOverwriteFiles1 {
            get {
                return ResourceManager.GetString("MessageOverwriteFiles1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with processed SQL files {0}?.
        /// </summary>
        internal static string MessageOverwriteFiles2 {
            get {
                return ResourceManager.GetString("MessageOverwriteFiles2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} SQL files have been changed in {1}..
        /// </summary>
        internal static string MessageOverwriteFilesSummary {
            get {
                return ResourceManager.GetString("MessageOverwriteFilesSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files could not be updated. .
        /// </summary>
        internal static string MessageOverwriteFilesSummary1 {
            get {
                return ResourceManager.GetString("MessageOverwriteFilesSummary1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original files are available in {0}. .
        /// </summary>
        internal static string MessageOverwriteFilesSummary2 {
            get {
                return ResourceManager.GetString("MessageOverwriteFilesSummary2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0} of {1} statements in {2} of {3} files..
        /// </summary>
        internal static string MessageProcessingStatus {
            get {
                return ResourceManager.GetString("MessageProcessingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0} of {1}.
        /// </summary>
        internal static string MessageProcessingTraceFileStatus {
            get {
                return ResourceManager.GetString("MessageProcessingTraceFileStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process started at {0} -- UTC -&gt; {1} ... .
        /// </summary>
        internal static string MessageProcessStarted {
            get {
                return ResourceManager.GetString("MessageProcessStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to generate SQL script?.
        /// </summary>
        internal static string MessageReadyToGenerate {
            get {
                return ResourceManager.GetString("MessageReadyToGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  second.
        /// </summary>
        internal static string MessageSecond {
            get {
                return ResourceManager.GetString("MessageSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  seconds.
        /// </summary>
        internal static string MessageSeconds {
            get {
                return ResourceManager.GetString("MessageSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting objects by dependency ....
        /// </summary>
        internal static string MessageSorting {
            get {
                return ResourceManager.GetString("MessageSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition Functions.
        /// </summary>
        internal static string ObjectTypePartitionFunctions {
            get {
                return ResourceManager.GetString("ObjectTypePartitionFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition Schemes.
        /// </summary>
        internal static string ObjectTypePartitionSchemes {
            get {
                return ResourceManager.GetString("ObjectTypePartitionSchemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Roles.
        /// </summary>
        internal static string ObjectTypeRoles {
            get {
                return ResourceManager.GetString("ObjectTypeRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schemas.
        /// </summary>
        internal static string ObjectTypeSchemas {
            get {
                return ResourceManager.GetString("ObjectTypeSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Assemblies.
        /// </summary>
        internal static string ObjectTypeSQLAssemblies {
            get {
                return ResourceManager.GetString("ObjectTypeSQLAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored Procedures.
        /// </summary>
        internal static string ObjectTypeStoredProcedures {
            get {
                return ResourceManager.GetString("ObjectTypeStoredProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synonyms.
        /// </summary>
        internal static string ObjectTypeSynonyms {
            get {
                return ResourceManager.GetString("ObjectTypeSynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        internal static string ObjectTypeTables {
            get {
                return ResourceManager.GetString("ObjectTypeTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggers.
        /// </summary>
        internal static string ObjectTypeTriggers {
            get {
                return ResourceManager.GetString("ObjectTypeTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined Functions.
        /// </summary>
        internal static string ObjectTypeUDF {
            get {
                return ResourceManager.GetString("ObjectTypeUDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined Data Types.
        /// </summary>
        internal static string ObjectTypeUDT {
            get {
                return ResourceManager.GetString("ObjectTypeUDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined Table Types.
        /// </summary>
        internal static string ObjectTypeUDTT {
            get {
                return ResourceManager.GetString("ObjectTypeUDTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        internal static string ObjectTypeViews {
            get {
                return ResourceManager.GetString("ObjectTypeViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Schema Collections.
        /// </summary>
        internal static string ObjectTypeXMLSchemaCollections {
            get {
                return ResourceManager.GetString("ObjectTypeXMLSchemaCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic 5 (DTUs).
        /// </summary>
        internal static string PerformanceLevelBasicFiveDTUs {
            get {
                return ResourceManager.GetString("PerformanceLevelBasicFiveDTUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P1 (100 DTUs).
        /// </summary>
        internal static string PerformanceLevelPremiumP1 {
            get {
                return ResourceManager.GetString("PerformanceLevelPremiumP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P2 (200 DTUs).
        /// </summary>
        internal static string PerformanceLevelPremiump2 {
            get {
                return ResourceManager.GetString("PerformanceLevelPremiump2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P3 (800 DTUs).
        /// </summary>
        internal static string PerformanceLevelPremiumP3 {
            get {
                return ResourceManager.GetString("PerformanceLevelPremiumP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0 (10 DTUs).
        /// </summary>
        internal static string PerformanceLevelStandardS0 {
            get {
                return ResourceManager.GetString("PerformanceLevelStandardS0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S1 (20 DTUs).
        /// </summary>
        internal static string PerformanceLevelStandardS1 {
            get {
                return ResourceManager.GetString("PerformanceLevelStandardS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S2 (50 DTUs).
        /// </summary>
        internal static string PerformanceLevelStandardS2 {
            get {
                return ResourceManager.GetString("PerformanceLevelStandardS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3 (100 DTUs).
        /// </summary>
        internal static string PerformanceLevelStandardS3 {
            get {
                return ResourceManager.GetString("PerformanceLevelStandardS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of original T-SQL files : {0}.
        /// </summary>
        internal static string rtbMessageOverwriteCopyOfOriginalFiles {
            get {
                return ResourceManager.GetString("rtbMessageOverwriteCopyOfOriginalFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed T-SQL files: {0}.
        /// </summary>
        internal static string rtbMessageOverwriteImpactedFiles {
            get {
                return ResourceManager.GetString("rtbMessageOverwriteImpactedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original T-SQL files : {0}.
        /// </summary>
        internal static string rtbMessageOverwriteOriginalFiles {
            get {
                return ResourceManager.GetString("rtbMessageOverwriteOriginalFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} T-SQL file(s) are impacted..
        /// </summary>
        internal static string rtbOverwriteFileMessageCountImpactedFiles {
            get {
                return ResourceManager.GetString("rtbOverwriteFileMessageCountImpactedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save SQL Azure Results.
        /// </summary>
        internal static string SaveAzureResults {
            get {
                return ResourceManager.GetString("SaveAzureResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Results Summary.
        /// </summary>
        internal static string SaveResults {
            get {
                return ResourceManager.GetString("SaveResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save SQL Script.
        /// </summary>
        internal static string SaveSQLScript {
            get {
                return ResourceManager.GetString("SaveSQLScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Database.
        /// </summary>
        internal static string SelectDatabase {
            get {
                return ResourceManager.GetString("SelectDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to database.windows.net.
        /// </summary>
        internal static string SQLAzureCloudName {
            get {
                return ResourceManager.GetString("SQLAzureCloudName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Server -- {0}.
        /// </summary>
        internal static string TargetServer {
            get {
                return ResourceManager.GetString("TargetServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Script.
        /// </summary>
        internal static string TitleExecuteScript {
            get {
                return ResourceManager.GetString("TitleExecuteScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Script.
        /// </summary>
        internal static string TitleGenerateScript {
            get {
                return ResourceManager.GetString("TitleGenerateScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string TreeNodeDatabase {
            get {
                return ResourceManager.GetString("TreeNodeDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted objects will not be scripted.
        /// </summary>
        internal static string TreeNodeEncrypted {
            get {
                return ResourceManager.GetString("TreeNodeEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string TreeNodeGeneral {
            get {
                return ResourceManager.GetString("TreeNodeGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include If Not Exists -- .
        /// </summary>
        internal static string TreeNodeIfNotExists {
            get {
                return ResourceManager.GetString("TreeNodeIfNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        internal static string TreeNodeObjects {
            get {
                return ResourceManager.GetString("TreeNodeObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string TreeNodeOptions {
            get {
                return ResourceManager.GetString("TreeNodeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Collation -- {0}.
        /// </summary>
        internal static string TreeNodeScriptCollation {
            get {
                return ResourceManager.GetString("TreeNodeScriptCollation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Check Constraints -- {0}.
        /// </summary>
        internal static string TreeNodeScriptConstraints {
            get {
                return ResourceManager.GetString("TreeNodeScriptConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Table / Data -- {0}.
        /// </summary>
        internal static string TreeNodeScriptData {
            get {
                return ResourceManager.GetString("TreeNodeScriptData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Defaults -- .
        /// </summary>
        internal static string TreeNodeScriptDefaults {
            get {
                return ResourceManager.GetString("TreeNodeScriptDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script DROP and CREATE -- .
        /// </summary>
        internal static string TreeNodeScriptDropCreate {
            get {
                return ResourceManager.GetString("TreeNodeScriptDropCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Extended Properties -- .
        /// </summary>
        internal static string TreeNodeScriptExtendedProperties {
            get {
                return ResourceManager.GetString("TreeNodeScriptExtendedProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Foreign Keys -- {0}.
        /// </summary>
        internal static string TreeNodeScriptForeignKeys {
            get {
                return ResourceManager.GetString("TreeNodeScriptForeignKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Headers -- .
        /// </summary>
        internal static string TreeNodeScriptHeaders {
            get {
                return ResourceManager.GetString("TreeNodeScriptHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Indexes -- {0}.
        /// </summary>
        internal static string TreeNodeScriptIndexes {
            get {
                return ResourceManager.GetString("TreeNodeScriptIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Primary Keys -- {0}.
        /// </summary>
        internal static string TreeNodeScriptPrimaryKey {
            get {
                return ResourceManager.GetString("TreeNodeScriptPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Unique Keys -- {0}.
        /// </summary>
        internal static string TreeNodeScriptUniqueKeys {
            get {
                return ResourceManager.GetString("TreeNodeScriptUniqueKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table / View Options.
        /// </summary>
        internal static string TreeNodeTableView {
            get {
                return ResourceManager.GetString("TreeNodeTableView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSQL Compatibility Checks.
        /// </summary>
        internal static string TreeNodeTSQLCompatibility {
            get {
                return ResourceManager.GetString("TreeNodeTSQLCompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Process.
        /// </summary>
        internal static string WizardAction {
            get {
                return ResourceManager.GetString("WizardAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the process you want the wizard to walk you through..
        /// </summary>
        internal static string WizardActionDesc {
            get {
                return ResourceManager.GetString("WizardActionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Objects.
        /// </summary>
        internal static string WizardActionObjectTypes {
            get {
                return ResourceManager.GetString("WizardActionObjectTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select database objects to script.
        /// </summary>
        internal static string WizardActionObjectTypesDesc {
            get {
                return ResourceManager.GetString("WizardActionObjectTypesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite T-SQL Files.
        /// </summary>
        internal static string WizardActionOverwriteFiles {
            get {
                return ResourceManager.GetString("WizardActionOverwriteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite original T-SQL files?.
        /// </summary>
        internal static string WizardActionOverwriteFilesDailogConfirmation {
            get {
                return ResourceManager.GetString("WizardActionOverwriteFilesDailogConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite original T-SQL files with the processed files..
        /// </summary>
        internal static string WizardActionOverwriteFilesDesc {
            get {
                return ResourceManager.GetString("WizardActionOverwriteFilesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results Summary.
        /// </summary>
        internal static string WizardActionResultsSummary {
            get {
                return ResourceManager.GetString("WizardActionResultsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripting and Analysis Summary.
        /// </summary>
        internal static string WizardActionResultsSummaryDesc {
            get {
                return ResourceManager.GetString("WizardActionResultsSummaryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Wizard Summary.
        /// </summary>
        internal static string WizardActionScriptWizardSummary {
            get {
                return ResourceManager.GetString("WizardActionScriptWizardSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review your selections for the wizard..
        /// </summary>
        internal static string WizardActionScriptWizardSummaryDesc {
            get {
                return ResourceManager.GetString("WizardActionScriptWizardSummaryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Source.
        /// </summary>
        internal static string WizardActionSelectSource {
            get {
                return ResourceManager.GetString("WizardActionSelectSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the source you want to script..
        /// </summary>
        internal static string WizardActionSelectSourceDesc {
            get {
                return ResourceManager.GetString("WizardActionSelectSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Target Server Connection.
        /// </summary>
        internal static string WizardActionSetupTargetConnection {
            get {
                return ResourceManager.GetString("WizardActionSetupTargetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter information for connection to Target Server..
        /// </summary>
        internal static string WizardActionSetupTargetConnectionDesc {
            get {
                return ResourceManager.GetString("WizardActionSetupTargetConnectionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Server Response.
        /// </summary>
        internal static string WizardActionTargetResults {
            get {
                return ResourceManager.GetString("WizardActionTargetResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results from T-SQL against Target Server.
        /// </summary>
        internal static string WizardActionTargetResultsDesc {
            get {
                return ResourceManager.GetString("WizardActionTargetResultsDesc", resourceCulture);
            }
        }
    }
}
